2024-11-03 08:08:48,483 : INFO : root : Loading config.
2024-11-03 08:08:48,510 : INFO : ConfigProcessor : Config spec file cache created: /tmp/config_spec.mpf_cache
2024-11-03 08:08:48,511 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-11-03 08:08:48,511 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/mpfconfig.yaml.
2024-11-03 08:08:48,517 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/mpfconfig.yaml
2024-11-03 08:08:48,517 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/config/config.yaml.
2024-11-03 08:08:48,522 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/config/config.yaml
2024-11-03 08:08:48,522 : ERROR : ConfigProcessor : Config section 'slides' is removed in MPF 0.80 and will be ignored.
2024-11-03 08:08:48,523 : INFO : ConfigProcessor : Config file cache created: /tmp/248da7825a7099821037453685569d45.mpf_cache
2024-11-03 08:08:48,576 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/attract/config/attract.yaml.
2024-11-03 08:08:48,576 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/attract/config/attract.yaml
2024-11-03 08:08:48,576 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/attract/config/attract.yaml.
2024-11-03 08:08:48,577 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/attract/config/attract.yaml
2024-11-03 08:08:48,577 : INFO : ConfigProcessor : Config file cache created: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-03 08:08:48,578 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/game/config/game.yaml.
2024-11-03 08:08:48,578 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/game/config/game.yaml
2024-11-03 08:08:48,578 : INFO : ConfigProcessor : Config file cache created: /tmp/03ef85df1864fb5ef5b7e38cbf9eb8a8.mpf_cache
2024-11-03 08:08:48,578 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/base/config/base.yaml.
2024-11-03 08:08:48,581 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/base/config/base.yaml
2024-11-03 08:08:48,581 : INFO : ConfigProcessor : Config file cache created: /tmp/6dcc9600f5dbf9a99f5346cc5ca34ea9.mpf_cache
2024-11-03 08:08:48,581 : INFO : ConfigProcessor : Loading config from cache: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-03 08:08:48,582 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/attract/shows/./attract_light_show.yaml.
2024-11-03 08:08:48,582 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/attract/shows/./attract_light_show.yaml
2024-11-03 08:08:48,583 : INFO : ConfigProcessor : Config file cache created: /tmp/2e5ac6493c6686883ff244e5da957f67.mpf_cache
2024-11-03 08:08:48,583 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-11-03 08:08:48,583 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-11-03-08-08-48-mpf-caw-System-Product-Name.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': '/home/caw/pinball/hauntedhouse/logs/2024-11-03-08-08-48-mpf-caw-System-Product-Name.log'}
2024-11-03 08:08:48,583 : INFO : Machine : MPF path: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf
2024-11-03 08:08:48,583 : INFO : Machine : Machine path: /home/caw/pinball/hauntedhouse
2024-11-03 08:08:48,583 : INFO : Machine : Platform: linux
2024-11-03 08:08:48,583 : INFO : Machine : Python executable location: /home/caw/miniconda3/envs/envp311/bin/python
2024-11-03 08:08:48,583 : INFO : Machine : Python version: 3.11.10 (64-bit)
2024-11-03 08:08:48,583 : INFO : Machine : Initializing MPF...
2024-11-03 08:08:48,592 : ERROR : Machine : Failed to initialize MPF
Traceback (most recent call last):
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/platforms/p_roc_common.py", line 31, in <module>
    import pinproc
ModuleNotFoundError: No module named 'pinproc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/platforms/p_roc_common.py", line 41, in <module>
    raise ImportError
ImportError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 686, in initialize_mpf
    raise init.exception()
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 248, in initialize
    await self.initialize_core_and_hardware()
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 234, in initialize_core_and_hardware
    self._load_hardware_platforms()
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 490, in _load_hardware_platforms
    self.add_platform(hardware_platform)
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 620, in add_platform
    self.hardware_platforms[name] = hardware_platform(self)
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/platforms/p3_roc.py", line 113, in __init__
    super().__init__(machine)
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/platforms/p_roc_common.py", line 180, in __init__
    raise MpfRuntimeError('Could not import "pinproc". Either the library is not installed or is missing '
mpf.exceptions.runtime_error.MpfRuntimeError: Runtime Error in P-Roc: Could not import "pinproc". Either the library is not installed or is missing some of its dependencies. Check the install instructions for your OS in Multimorphic section of the MPF docs. You can run mpf with "-X" to use virtual hardware in the meantime. Error Code: RE-P-Roc-3 (https://missionpinball.org/logs)
2024-11-03 08:08:48,595 : INFO : root : MPF run loop ended.
