2024-11-03 09:57:44,908 : INFO : root : Loading config.
2024-11-03 09:57:44,936 : INFO : ConfigProcessor : Config spec file cache created: /tmp/config_spec.mpf_cache
2024-11-03 09:57:44,936 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-11-03 09:57:44,936 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/mpfconfig.yaml.
2024-11-03 09:57:44,942 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/mpfconfig.yaml
2024-11-03 09:57:44,942 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/config/config.yaml.
2024-11-03 09:57:44,948 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/config/config.yaml
2024-11-03 09:57:44,948 : ERROR : ConfigProcessor : Config section 'slides' is removed in MPF 0.80 and will be ignored.
2024-11-03 09:57:44,949 : INFO : ConfigProcessor : Config file cache created: /tmp/248da7825a7099821037453685569d45.mpf_cache
2024-11-03 09:57:45,019 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/attract/config/attract.yaml.
2024-11-03 09:57:45,020 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/attract/config/attract.yaml
2024-11-03 09:57:45,020 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/attract/config/attract.yaml.
2024-11-03 09:57:45,020 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/attract/config/attract.yaml
2024-11-03 09:57:45,020 : INFO : ConfigProcessor : Config file cache created: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-03 09:57:45,021 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/game/config/game.yaml.
2024-11-03 09:57:45,022 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/game/config/game.yaml
2024-11-03 09:57:45,022 : INFO : ConfigProcessor : Config file cache created: /tmp/03ef85df1864fb5ef5b7e38cbf9eb8a8.mpf_cache
2024-11-03 09:57:45,023 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/base/config/base.yaml.
2024-11-03 09:57:45,025 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/base/config/base.yaml
2024-11-03 09:57:45,025 : INFO : ConfigProcessor : Config file cache created: /tmp/6dcc9600f5dbf9a99f5346cc5ca34ea9.mpf_cache
2024-11-03 09:57:45,026 : INFO : ConfigProcessor : Loading config from cache: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-03 09:57:45,026 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/attract/shows/./attract_light_show.yaml.
2024-11-03 09:57:45,027 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/attract/shows/./attract_light_show.yaml
2024-11-03 09:57:45,027 : INFO : ConfigProcessor : Config file cache created: /tmp/2e5ac6493c6686883ff244e5da957f67.mpf_cache
2024-11-03 09:57:45,027 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-11-03 09:57:45,027 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-11-03-09-57-44-mpf-caw-System-Product-Name.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': '/home/caw/pinball/hauntedhouse/logs/2024-11-03-09-57-44-mpf-caw-System-Product-Name.log'}
2024-11-03 09:57:45,027 : INFO : Machine : MPF path: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf
2024-11-03 09:57:45,027 : INFO : Machine : Machine path: /home/caw/pinball/hauntedhouse
2024-11-03 09:57:45,027 : INFO : Machine : Platform: linux
2024-11-03 09:57:45,027 : INFO : Machine : Python executable location: /home/caw/miniconda3/envs/envp311/bin/python
2024-11-03 09:57:45,027 : INFO : Machine : Python version: 3.11.10 (64-bit)
2024-11-03 09:57:45,028 : INFO : Machine : Initializing MPF...
2024-11-03 09:57:45,109 : INFO : P-Roc : Connecting to P-ROC
2024-11-03 09:57:45,116 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:45,116 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:46,122 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:46,122 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:47,129 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:47,129 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:48,136 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:48,136 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:49,142 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:49,142 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:50,148 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:50,148 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:51,155 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:51,155 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:52,162 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:52,162 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:53,169 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:53,169 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:54,176 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:54,176 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:55,183 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:55,183 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:56,190 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:56,190 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:57,197 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-03 09:57:57,197 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-03 09:57:57,379 : INFO : Machine : Starting the main run loop with active modes: []
2024-11-03 09:57:57,379 : ERROR : root : 'attract'
Traceback (most recent call last):
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/commands/game.py", line 229, in __init__
    self.machine.run()
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 701, in run
    if not self.modes['attract'] in self.mode_controller.active_modes:
           ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'attract'
