2024-11-05 19:19:36,878 : INFO : root : Loading config.
2024-11-05 19:19:36,905 : INFO : ConfigProcessor : Config spec file cache created: /tmp/config_spec.mpf_cache
2024-11-05 19:19:36,905 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-11-05 19:19:36,906 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/mpfconfig.yaml.
2024-11-05 19:19:36,912 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/mpfconfig.yaml
2024-11-05 19:19:36,912 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/config/config.yaml.
2024-11-05 19:19:36,917 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/config/config.yaml
2024-11-05 19:19:36,918 : INFO : ConfigProcessor : Config file cache created: /tmp/248da7825a7099821037453685569d45.mpf_cache
2024-11-05 19:19:36,978 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/attract/config/attract.yaml.
2024-11-05 19:19:36,979 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/attract/config/attract.yaml
2024-11-05 19:19:36,979 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/attract/config/attract.yaml.
2024-11-05 19:19:36,979 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/attract/config/attract.yaml
2024-11-05 19:19:36,979 : INFO : ConfigProcessor : Config file cache created: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-05 19:19:36,980 : INFO : ConfigProcessor : Loading config from file /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/game/config/game.yaml.
2024-11-05 19:19:36,981 : INFO : ConfigProcessor : Loading config: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/modes/game/config/game.yaml
2024-11-05 19:19:36,981 : INFO : ConfigProcessor : Config file cache created: /tmp/03ef85df1864fb5ef5b7e38cbf9eb8a8.mpf_cache
2024-11-05 19:19:36,981 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/base/config/base.yaml.
2024-11-05 19:19:36,983 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/base/config/base.yaml
2024-11-05 19:19:36,983 : INFO : ConfigProcessor : Config file cache created: /tmp/6dcc9600f5dbf9a99f5346cc5ca34ea9.mpf_cache
2024-11-05 19:19:36,984 : INFO : ConfigProcessor : Loading config from cache: /tmp/95514865456cf95aac1ab02b2b9c91d4.mpf_cache
2024-11-05 19:19:36,984 : INFO : ConfigProcessor : Loading config from file /home/caw/pinball/hauntedhouse/modes/attract/shows/./attract_light_show.yaml.
2024-11-05 19:19:36,984 : INFO : ConfigProcessor : Loading config: /home/caw/pinball/hauntedhouse/modes/attract/shows/./attract_light_show.yaml
2024-11-05 19:19:36,984 : INFO : ConfigProcessor : Config file cache created: /tmp/2e5ac6493c6686883ff244e5da957f67.mpf_cache
2024-11-05 19:19:36,985 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev5
2024-11-05 19:19:36,985 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-11-05-19-19-36-mpf-caw-System-Product-Name.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': '/home/caw/pinball/hauntedhouse/logs/2024-11-05-19-19-36-mpf-caw-System-Product-Name.log'}
2024-11-05 19:19:36,985 : INFO : Machine : MPF path: /home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf
2024-11-05 19:19:36,985 : INFO : Machine : Machine path: /home/caw/pinball/hauntedhouse
2024-11-05 19:19:36,985 : INFO : Machine : Platform: linux
2024-11-05 19:19:36,985 : INFO : Machine : Python executable location: /home/caw/miniconda3/envs/envp311/bin/python
2024-11-05 19:19:36,985 : INFO : Machine : Python version: 3.11.10 (64-bit)
2024-11-05 19:19:36,985 : INFO : Machine : Initializing MPF...
2024-11-05 19:19:37,060 : INFO : P-Roc : Connecting to P-ROC
2024-11-05 19:19:37,067 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-05 19:19:37,067 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-05 19:19:38,073 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-05 19:19:38,073 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-05 19:19:39,080 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-05 19:19:39,080 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-05 19:19:40,086 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-05 19:19:40,087 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-05 19:19:41,093 : WARNING : P-Roc : Failed to instantiate pinproc.PinPROC(7): Unable to open ftdi device: -3: device not found. Is your P/P3-Roc connected and powered up?
2024-11-05 19:19:41,093 : INFO : P-Roc : Will retry creating PinPROC in 1s.
2024-11-05 19:19:41,310 : INFO : Machine : Starting the main run loop with active modes: []
2024-11-05 19:19:41,310 : ERROR : root : 'attract'
Traceback (most recent call last):
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/commands/game.py", line 229, in __init__
    self.machine.run()
  File "/home/caw/miniconda3/envs/envp311/lib/python3.11/site-packages/mpf/core/machine.py", line 701, in run
    if not self.modes['attract'] in self.mode_controller.active_modes:
           ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'attract'
